from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from fastapi import HTTPException
import datetime
import logging

from app.schemas.simulation import SimulationReport, PRESET_SEGMENTS_BY_ID
from app.models.simulation_report import SimulationReport as SimulationReportModel
from app.models.creative import Creative
from app.services.ai.ai_router import AIRouter
from app.models.user import User
from app.services.billing_service import (
    assert_can_spend,
    charge,
    refund,
    SIMULATION_CREDIT_COST,
    ESTIMATED_PROVIDER_COSTS,
)

logger = logging.getLogger(__name__)


async def simulate_creative_for_audiences(
    db: AsyncSession,
    creative_id: str,
    segment_ids: list,
    user: User,
    byok_key: str = None,
    byok_provider: str = None,
) -> SimulationReport:
    # 1. Fetch creative
    result = await db.execute(select(Creative).where(Creative.id == creative_id))
    creative_model = result.scalar_one_or_none()
    if not creative_model:
        raise HTTPException(status_code=404, detail="Creative not found")

    # 2. Resolve preset personas — reject anything not in the fixed catalogue
    # rather than accepting free-text audience descriptions from the client.
    segments = []
    for seg_id in segment_ids:
        segment = PRESET_SEGMENTS_BY_ID.get(seg_id)
        if not segment:
            raise HTTPException(status_code=422, detail=f"Unknown audience segment: {seg_id}")
        segments.append(segment)
    if not segments:
        raise HTTPException(status_code=422, detail="At least one audience segment is required")

    # 3. Server-side credit & feature gate (if not using BYOK)
    cost = 0.0 if (byok_key and byok_provider) else SIMULATION_CREDIT_COST
    org, plan = await assert_can_spend(
        db,
        user=user,
        required_credits=cost,
        feature_name="intelligence",
        lock_row=True,
    )

    provider = await AIRouter.get_provider_for_user(db, user, byok_key, byok_provider)

    from app.schemas.creative import Creative as CreativeSchema, Scores, CreativeMetrics
    creative_schema = CreativeSchema(
        id=creative_model.id,
        brand_id=creative_model.brand_id,
        platform=creative_model.platform,
        format=creative_model.format,
        headline=creative_model.headline or "",
        body=creative_model.body or "",
        cta=creative_model.cta or "",
        first_seen=creative_model.first_seen or "",
        last_seen=creative_model.last_seen or "",
        days_active=creative_model.days_active or 1,
        variant_count=creative_model.variant_count or 1,
        scores=Scores(),
        metrics=CreativeMetrics(),
        pattern_ids=[],
    )

    try:
        sim_result = await provider.simulate_audience_reactions(creative_schema, segments)
        provider_name = getattr(provider, "model", "unknown")

        # 4. Deduct credit only after a real simulation result exists
        if cost > 0:
            await charge(
                db=db,
                org=org,
                user_id=user.id,
                amount=cost,
                provider=provider_name,
                operation="audience_simulation",
                units=1.0,
                cost_usd=ESTIMATED_PROVIDER_COSTS.get("groq_tokens", 0.0006) * 1500,
                job_id=None,
                metadata={"creative_id": creative_id, "segment_ids": segment_ids},
            )
        else:
            await AIRouter.log_usage(db, user.id, provider_name, org_id=org.id, tokens=0)

        assumptions = [
            "Synthetic personas generated by an LLM, not real consumer research or panel data.",
            "Reactions are directional signals to catch objections and risks before spend, not a forecast of real audience behavior.",
        ]

        report_schema = SimulationReport(
            id=f"sim_{datetime.datetime.now().timestamp()}",
            creative_id=creative_id,
            simulation_id=f"sim_{datetime.datetime.now().timestamp()}",
            model_version=provider_name,
            assumptions=assumptions,
            evidence_creative_ids=[creative_id],
            generated_at=sim_result["generated_at"],
            segment_reactions=sim_result["segment_reactions"],
            recommended_angles=sim_result["recommended_angles"],
        )

        # 5. Save to DB. If persistence fails after a charge, refund — the
        # user must never pay for a simulation they did not receive.
        try:
            new_report = SimulationReportModel(
                id=report_schema.id,
                creative_id=creative_id,
                org_id=org.id,
                user_id=user.id,
                data_source=report_schema.data_source,
                is_estimated=report_schema.is_estimated,
                model_version=report_schema.model_version,
                assumptions=report_schema.assumptions,
                evidence_creative_ids=report_schema.evidence_creative_ids,
                segment_reactions=[r.model_dump() for r in report_schema.segment_reactions],
                recommended_angles=report_schema.recommended_angles,
                generated_at=report_schema.generated_at,
            )
            db.add(new_report)
            await db.commit()
        except Exception:
            if cost > 0:
                await refund(db, org.id, cost, "simulation_persist_failed", None)
            raise

        return report_schema
    except HTTPException:
        raise
    except Exception as e:
        logger.error(
            "Audience simulation failed (creative=%s user=%s): %s",
            creative_id, user.id, e,
        )
        try:
            await AIRouter.log_failure(
                db,
                user_id=user.id,
                provider_name=getattr(provider, "model", "unknown"),
                operation="audience_simulation",
                org_id=org.id,
                error=str(e),
            )
        except Exception:
            logger.exception("Failed to record audience simulation failure log")
        raise HTTPException(
            status_code=503,
            detail={
                "code": "simulation_unavailable",
                "message": "Audience simulation is temporarily unavailable — the AI provider could not be reached. No credits were charged. Please try again shortly.",
            },
        )
