"""Add is_suspended to users

Revision ID: 46af201944fd
Revises: 48ce41ebc764
Create Date: 2026-08-23 19:10:20.261731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46af201944fd'
down_revision: Union[str, Sequence[str], None] = '48ce41ebc764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('creatives', 'source_type')
    op.drop_column('creatives', 'is_impression_estimate')
    op.add_column('users', sa.Column('is_suspended', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_suspended')
    op.add_column('creatives', sa.Column('is_impression_estimate', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('creatives', sa.Column('source_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
