"""add_billing_and_gated_features

Revision ID: 48ce41ebc764
Revises: 26d99f8467f6
Create Date: 2026-08-23 03:53:47.269637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48ce41ebc764'
down_revision: Union[str, Sequence[str], None] = '26d99f8467f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('credit_allowance', sa.Integer(), nullable=True),
    sa.Column('price_per_credit', sa.Float(), nullable=True),
    sa.Column('feature_flags', sa.JSON(), nullable=True),
    sa.Column('created_by_admin_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('prefix', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=False)
    op.create_index(op.f('ix_api_keys_org_id'), 'api_keys', ['org_id'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_org_id'), 'notifications', ['org_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('organization_invites',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('invited_by_user_id', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_invites_email'), 'organization_invites', ['email'], unique=False)
    op.create_index(op.f('ix_organization_invites_org_id'), 'organization_invites', ['org_id'], unique=False)
    op.create_index(op.f('ix_organization_invites_token'), 'organization_invites', ['token'], unique=True)
    op.create_table('organization_members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_members_org_id'), 'organization_members', ['org_id'], unique=False)
    op.create_index(op.f('ix_organization_members_user_id'), 'organization_members', ['user_id'], unique=False)
    op.create_table('saved_creatives',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('creative_id', sa.String(), nullable=False),
    sa.Column('collection_name', sa.String(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_creatives_collection_name'), 'saved_creatives', ['collection_name'], unique=False)
    op.create_index(op.f('ix_saved_creatives_created_at'), 'saved_creatives', ['created_at'], unique=False)
    op.create_index(op.f('ix_saved_creatives_creative_id'), 'saved_creatives', ['creative_id'], unique=False)
    op.create_index(op.f('ix_saved_creatives_org_id'), 'saved_creatives', ['org_id'], unique=False)
    op.create_index(op.f('ix_saved_creatives_user_id'), 'saved_creatives', ['user_id'], unique=False)
    op.add_column('creatives', sa.Column('is_estimated', sa.Boolean(), nullable=True))
    op.add_column('creatives', sa.Column('data_source', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('plan_id', sa.String(), server_default='plan_trial_default', nullable=False))
    op.add_column('organizations', sa.Column('credit_balance', sa.Float(), server_default='25.0', nullable=False))
    op.add_column('organizations', sa.Column('credits_used', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('organizations', sa.Column('custom_feature_flags', sa.JSON(), nullable=True))
    op.add_column('organizations', sa.Column('status', sa.String(), server_default='active', nullable=False))
    op.add_column('usage_logs', sa.Column('job_id', sa.String(), nullable=True))
    op.add_column('usage_logs', sa.Column('operation', sa.String(), server_default='discover_search', nullable=False))
    op.add_column('usage_logs', sa.Column('units', sa.Float(), nullable=True))
    op.add_column('usage_logs', sa.Column('cost_usd', sa.Float(), nullable=True))
    op.add_column('usage_logs', sa.Column('credits_deducted', sa.Float(), nullable=True))
    op.add_column('usage_logs', sa.Column('metadata_json', sa.JSON(), nullable=True))
    op.alter_column('usage_logs', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_usage_logs_job_id'), 'usage_logs', ['job_id'], unique=False)
    op.create_index(op.f('ix_usage_logs_provider'), 'usage_logs', ['provider'], unique=False)
    
    # Seed default plans
    plans_table = sa.table(
        'plans',
        sa.column('id', sa.String),
        sa.column('name', sa.String),
        sa.column('type', sa.String),
        sa.column('credit_allowance', sa.Integer),
        sa.column('price_per_credit', sa.Float),
        sa.column('feature_flags', sa.JSON)
    )
    
    op.bulk_insert(plans_table, [
        {
            "id": "plan_trial_default",
            "name": "7-Day Free Trial",
            "type": "trial",
            "credit_allowance": 25,
            "price_per_credit": 0.0,
            "feature_flags": {
                "discover": True,
                "intelligence": True,
                "create": True,
                "performance": True,
                "swipe_files": True,
                "team_accounts": False,
                "public_api": False
            }
        },
        {
            "id": "plan_payg_default",
            "name": "Pay As You Go",
            "type": "pay_as_you_go",
            "credit_allowance": 0,
            "price_per_credit": 0.01,
            "feature_flags": {
                "discover": True,
                "intelligence": True,
                "create": True,
                "performance": True,
                "swipe_files": True,
                "team_accounts": True,
                "public_api": False
            }
        },
        {
            "id": "plan_enterprise_custom",
            "name": "Enterprise Custom",
            "type": "custom",
            "credit_allowance": 500,
            "price_per_credit": 0.008,
            "feature_flags": {
                "discover": True,
                "intelligence": True,
                "create": True,
                "performance": True,
                "swipe_files": True,
                "team_accounts": True,
                "public_api": True
            }
        }
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_logs_provider'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_job_id'), table_name='usage_logs')
    op.alter_column('usage_logs', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('usage_logs', 'metadata_json')
    op.drop_column('usage_logs', 'credits_deducted')
    op.drop_column('usage_logs', 'cost_usd')
    op.drop_column('usage_logs', 'units')
    op.drop_column('usage_logs', 'operation')
    op.drop_column('usage_logs', 'job_id')
    op.drop_column('organizations', 'status')
    op.drop_column('organizations', 'custom_feature_flags')
    op.drop_column('organizations', 'credits_used')
    op.drop_column('organizations', 'credit_balance')
    op.drop_column('organizations', 'plan_id')
    op.drop_column('creatives', 'data_source')
    op.drop_column('creatives', 'is_estimated')
    op.drop_index(op.f('ix_saved_creatives_user_id'), table_name='saved_creatives')
    op.drop_index(op.f('ix_saved_creatives_org_id'), table_name='saved_creatives')
    op.drop_index(op.f('ix_saved_creatives_creative_id'), table_name='saved_creatives')
    op.drop_index(op.f('ix_saved_creatives_created_at'), table_name='saved_creatives')
    op.drop_index(op.f('ix_saved_creatives_collection_name'), table_name='saved_creatives')
    op.drop_table('saved_creatives')
    op.drop_index(op.f('ix_organization_members_user_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_org_id'), table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_organization_invites_token'), table_name='organization_invites')
    op.drop_index(op.f('ix_organization_invites_org_id'), table_name='organization_invites')
    op.drop_index(op.f('ix_organization_invites_email'), table_name='organization_invites')
    op.drop_table('organization_invites')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_org_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_org_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('plans')
    # ### end Alembic commands ###
