"""Initial backend scaffold

Revision ID: b04f12968b0c
Revises: 
Create Date: 2026-08-20 04:53:24.768124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b04f12968b0c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('trial_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrape_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('stage_label', sa.String(), nullable=True),
    sa.Column('stage_index', sa.Integer(), nullable=True),
    sa.Column('stages_total', sa.Integer(), nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('error_msg', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('creatives',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('brand_id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('cta', sa.String(), nullable=True),
    sa.Column('landing_domain', sa.String(), nullable=True),
    sa.Column('thumbnail_ratio', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.String(), nullable=True),
    sa.Column('last_seen', sa.String(), nullable=True),
    sa.Column('days_active', sa.Integer(), nullable=True),
    sa.Column('variant_count', sa.Integer(), nullable=True),
    sa.Column('impressions_est', sa.Integer(), nullable=True),
    sa.Column('spend_band', sa.String(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('ctr_est', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['scrape_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patterns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('family', sa.String(), nullable=False),
    sa.Column('prevalence', sa.Float(), nullable=False),
    sa.Column('lift_index', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['scrape_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_insights',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('creative_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('reasons', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_creative_ids', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_at', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('creative_scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('creative_id', sa.String(), nullable=False),
    sa.Column('hook', sa.Float(), nullable=True),
    sa.Column('clarity', sa.Float(), nullable=True),
    sa.Column('retention', sa.Float(), nullable=True),
    sa.Column('composite', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creative_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('creative_scores')
    op.drop_table('ai_insights')
    op.drop_table('patterns')
    op.drop_table('creatives')
    op.drop_table('scrape_jobs')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
