"""rename source_type and is_impression_estimate

Revision ID: dd4ab34b6438
Revises: 26d99f8467f6
Create Date: 2026-08-23 03:13:15.376304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd4ab34b6438'
down_revision: Union[str, Sequence[str], None] = '26d99f8467f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_keys_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_org'), table_name='api_keys')
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=False)
    op.create_index(op.f('ix_api_keys_org_id'), 'api_keys', ['org_id'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.drop_constraint(op.f('api_keys_org_id_fkey'), 'api_keys', type_='foreignkey')
    op.drop_constraint(op.f('api_keys_user_id_fkey'), 'api_keys', type_='foreignkey')
    op.create_foreign_key(None, 'api_keys', 'organizations', ['org_id'], ['id'])
    op.create_foreign_key(None, 'api_keys', 'users', ['user_id'], ['id'])
    op.add_column('creatives', sa.Column('is_estimated', sa.Boolean(), nullable=True))
    op.add_column('creatives', sa.Column('data_source', sa.String(), nullable=True))
    op.drop_column('creatives', 'source_type')
    op.drop_column('creatives', 'is_impression_estimate')
    op.drop_index(op.f('ix_notifications_user_read'), table_name='notifications')
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_org_id'), 'notifications', ['org_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.drop_constraint(op.f('notifications_org_id_fkey'), 'notifications', type_='foreignkey')
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'organizations', ['org_id'], ['id'])
    op.drop_index(op.f('ix_org_invites_token'), table_name='organization_invites')
    op.drop_constraint(op.f('organization_invites_token_key'), 'organization_invites', type_='unique')
    op.create_index(op.f('ix_organization_invites_email'), 'organization_invites', ['email'], unique=False)
    op.create_index(op.f('ix_organization_invites_org_id'), 'organization_invites', ['org_id'], unique=False)
    op.create_index(op.f('ix_organization_invites_token'), 'organization_invites', ['token'], unique=True)
    op.drop_constraint(op.f('organization_invites_org_id_fkey'), 'organization_invites', type_='foreignkey')
    op.drop_constraint(op.f('organization_invites_invited_by_user_id_fkey'), 'organization_invites', type_='foreignkey')
    op.create_foreign_key(None, 'organization_invites', 'users', ['invited_by_user_id'], ['id'])
    op.create_foreign_key(None, 'organization_invites', 'organizations', ['org_id'], ['id'])
    op.drop_index(op.f('ix_org_members_org_user'), table_name='organization_members')
    op.create_index(op.f('ix_organization_members_org_id'), 'organization_members', ['org_id'], unique=False)
    op.create_index(op.f('ix_organization_members_user_id'), 'organization_members', ['user_id'], unique=False)
    op.drop_constraint(op.f('organization_members_user_id_fkey'), 'organization_members', type_='foreignkey')
    op.drop_constraint(op.f('organization_members_org_id_fkey'), 'organization_members', type_='foreignkey')
    op.create_foreign_key(None, 'organization_members', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'organization_members', 'organizations', ['org_id'], ['id'])
    op.alter_column('organizations', 'plan_id',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'plan_trial_default'::character varying"))
    op.alter_column('organizations', 'credit_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('25.0'))
    op.alter_column('organizations', 'credits_used',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('organizations', 'custom_feature_flags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('organizations', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('plans', 'feature_flags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('saved_creatives', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index(op.f('ix_saved_creatives_creative'), table_name='saved_creatives')
    op.drop_index(op.f('ix_saved_creatives_org'), table_name='saved_creatives')
    op.drop_index(op.f('ix_saved_creatives_user'), table_name='saved_creatives')
    op.create_index(op.f('ix_saved_creatives_collection_name'), 'saved_creatives', ['collection_name'], unique=False)
    op.create_index(op.f('ix_saved_creatives_created_at'), 'saved_creatives', ['created_at'], unique=False)
    op.create_index(op.f('ix_saved_creatives_creative_id'), 'saved_creatives', ['creative_id'], unique=False)
    op.create_index(op.f('ix_saved_creatives_org_id'), 'saved_creatives', ['org_id'], unique=False)
    op.create_index(op.f('ix_saved_creatives_user_id'), 'saved_creatives', ['user_id'], unique=False)
    op.drop_constraint(op.f('saved_creatives_user_id_fkey'), 'saved_creatives', type_='foreignkey')
    op.drop_constraint(op.f('saved_creatives_creative_id_fkey'), 'saved_creatives', type_='foreignkey')
    op.drop_constraint(op.f('saved_creatives_org_id_fkey'), 'saved_creatives', type_='foreignkey')
    op.create_foreign_key(None, 'saved_creatives', 'creatives', ['creative_id'], ['id'])
    op.create_foreign_key(None, 'saved_creatives', 'organizations', ['org_id'], ['id'])
    op.create_foreign_key(None, 'saved_creatives', 'users', ['user_id'], ['id'])
    op.alter_column('usage_logs', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usage_logs', 'operation',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'discover_search'::character varying"))
    op.alter_column('usage_logs', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('ix_usage_logs_job_id'), 'usage_logs', ['job_id'], unique=False)
    op.create_index(op.f('ix_usage_logs_provider'), 'usage_logs', ['provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_logs_provider'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_job_id'), table_name='usage_logs')
    op.alter_column('usage_logs', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('usage_logs', 'operation',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'discover_search'::character varying"))
    op.alter_column('usage_logs', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'saved_creatives', type_='foreignkey')
    op.drop_constraint(None, 'saved_creatives', type_='foreignkey')
    op.drop_constraint(None, 'saved_creatives', type_='foreignkey')
    op.create_foreign_key(op.f('saved_creatives_org_id_fkey'), 'saved_creatives', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('saved_creatives_creative_id_fkey'), 'saved_creatives', 'creatives', ['creative_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('saved_creatives_user_id_fkey'), 'saved_creatives', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_saved_creatives_user_id'), table_name='saved_creatives')
    op.drop_index(op.f('ix_saved_creatives_org_id'), table_name='saved_creatives')
    op.drop_index(op.f('ix_saved_creatives_creative_id'), table_name='saved_creatives')
    op.drop_index(op.f('ix_saved_creatives_created_at'), table_name='saved_creatives')
    op.drop_index(op.f('ix_saved_creatives_collection_name'), table_name='saved_creatives')
    op.create_index(op.f('ix_saved_creatives_user'), 'saved_creatives', ['user_id'], unique=False)
    op.create_index(op.f('ix_saved_creatives_org'), 'saved_creatives', ['org_id'], unique=False)
    op.create_index(op.f('ix_saved_creatives_creative'), 'saved_creatives', ['creative_id'], unique=False)
    op.alter_column('saved_creatives', 'tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('plans', 'feature_flags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('organizations', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('organizations', 'custom_feature_flags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('organizations', 'credits_used',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('organizations', 'credit_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('25.0'))
    op.alter_column('organizations', 'plan_id',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'plan_trial_default'::character varying"))
    op.drop_constraint(None, 'organization_members', type_='foreignkey')
    op.drop_constraint(None, 'organization_members', type_='foreignkey')
    op.create_foreign_key(op.f('organization_members_org_id_fkey'), 'organization_members', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('organization_members_user_id_fkey'), 'organization_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_organization_members_user_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_org_id'), table_name='organization_members')
    op.create_index(op.f('ix_org_members_org_user'), 'organization_members', ['org_id', 'user_id'], unique=False)
    op.drop_constraint(None, 'organization_invites', type_='foreignkey')
    op.drop_constraint(None, 'organization_invites', type_='foreignkey')
    op.create_foreign_key(op.f('organization_invites_invited_by_user_id_fkey'), 'organization_invites', 'users', ['invited_by_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('organization_invites_org_id_fkey'), 'organization_invites', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_organization_invites_token'), table_name='organization_invites')
    op.drop_index(op.f('ix_organization_invites_org_id'), table_name='organization_invites')
    op.drop_index(op.f('ix_organization_invites_email'), table_name='organization_invites')
    op.create_unique_constraint(op.f('organization_invites_token_key'), 'organization_invites', ['token'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_org_invites_token'), 'organization_invites', ['token'], unique=False)
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('notifications_org_id_fkey'), 'notifications', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_org_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.create_index(op.f('ix_notifications_user_read'), 'notifications', ['user_id', 'is_read'], unique=False)
    op.add_column('creatives', sa.Column('is_impression_estimate', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('creatives', sa.Column('source_type', sa.VARCHAR(), server_default=sa.text("'ad'::character varying"), autoincrement=False, nullable=True))
    op.drop_column('creatives', 'data_source')
    op.drop_column('creatives', 'is_estimated')
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.create_foreign_key(op.f('api_keys_user_id_fkey'), 'api_keys', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('api_keys_org_id_fkey'), 'api_keys', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_org_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.create_index(op.f('ix_api_keys_org'), 'api_keys', ['org_id'], unique=False)
    op.create_index(op.f('ix_api_keys_hash'), 'api_keys', ['key_hash'], unique=False)
    # ### end Alembic commands ###
