import { delay, maybeFail, makeId } from "./latency"

/**
 * Mock synthetic-audience simulation service.
 *
 * Mirrors PRESET_SEGMENTS in backend/app/schemas/simulation.py — ids must
 * stay in sync since the API layer sends the same ids to the backend.
 * Every report is a rehearsal aid, not a real performance prediction, so
 * it always carries `data_source: "simulated"` and `is_estimated: true`.
 */
export const PRESET_SEGMENTS = [
  {
    id: "price_sensitive_skeptic",
    label: "Price-Sensitive Skeptic",
    description:
      "Compares every claim to cheaper alternatives, distrusts superlatives, and looks for the catch before considering a purchase.",
  },
  {
    id: "brand_loyalist",
    label: "Existing Brand Loyalist",
    description:
      "Already uses a competing or incumbent product, evaluates the ad against their current habit, and needs a concrete reason to switch.",
  },
  {
    id: "trend_driven_gen_z",
    label: "Trend-Driven Gen Z",
    description:
      "Scrolls fast, judges within 2 seconds, values authenticity and humor over polish, and is quick to call out anything that feels like a generic ad.",
  },
  {
    id: "busy_value_researcher",
    label: "Busy Value-Conscious Researcher",
    description:
      "Reads carefully but has little time, wants concrete specifics and proof over adjectives, and abandons ads that feel vague or exaggerated.",
  },
  {
    id: "early_adopter_enthusiast",
    label: "Early-Adopter Enthusiast",
    description:
      "Excited by new products and novel claims, but has seen many ad gimmicks before and can spot hype that isn't backed by substance.",
  },
  {
    id: "cautious_first_time_buyer",
    label: "Cautious First-Time Buyer",
    description:
      "Unfamiliar with the category, easily confused by jargon, and highly sensitive to anything that reads as risky, technical, or untrustworthy.",
  },
]

const segmentsById = PRESET_SEGMENTS.reduce((acc, s) => {
  acc[s.id] = s
  return acc
}, {})

function fabricateReaction(segment, creativeId) {
  // Deterministic-ish appeal so the same creative+segment always reads the
  // same in a demo, without pretending this is a real measurement.
  const seed = `${creativeId}:${segment.id}`.split("").reduce((a, c) => a + c.charCodeAt(0), 0)
  const appeal = 0.35 + ((seed % 50) / 100)

  return {
    segment_id: segment.id,
    segment_label: segment.label,
    appeal_score: Number(appeal.toFixed(2)),
    objections: [
      "The core claim isn't backed by a concrete number or proof point.",
      "Unclear what happens after the CTA is clicked.",
    ],
    confusing_claims: appeal < 0.55 ? ["The headline reads as a generic superlative rather than a specific benefit."] : [],
    credibility_assessment:
      appeal >= 0.6
        ? "Would likely trust this enough to keep watching, but wants more specifics before converting."
        : "Skeptical of the framing without more evidence; likely to scroll past.",
    compliance_risks: appeal < 0.4 ? ["Implied outcome claim may need a disclaimer on some ad platforms."] : [],
  }
}

const simulationService = {
  async listSegments() {
    await delay(150)
    return PRESET_SEGMENTS
  },

  /**
   * @param {string} creativeId
   * @param {{ segment_ids: string[] }} params
   */
  async simulate(creativeId, { segment_ids = [] } = {}) {
    await delay(900)
    maybeFail("Synthetic audience worker did not respond in time")

    const segments = segment_ids.map((id) => segmentsById[id]).filter(Boolean)
    const segment_reactions = segments.map((s) => fabricateReaction(s, creativeId))

    return {
      id: makeId("sim"),
      creative_id: creativeId,
      simulation_id: makeId("sim"),
      data_source: "simulated",
      is_estimated: true,
      model_version: "mock-persona-sim-0.1",
      assumptions: [
        "Synthetic personas generated by an LLM, not real consumer research or panel data.",
        "Reactions are directional signals to catch objections and risks before spend, not a forecast of real audience behavior.",
      ],
      evidence_creative_ids: [creativeId],
      generated_at: new Date().toISOString(),
      segment_reactions,
      recommended_angles: [
        "Lead with a specific, quantified proof point instead of a general claim.",
        "Clarify what the viewer gets immediately after tapping the CTA.",
      ],
    }
  },
}

export default simulationService
